apiVersion: v1
kind: Service                # Defines to create Service type object
metadata:
  name: demoservice           # Name of the service
spec:
  selector:
    name: deployment          #Apply this service to any pods which has the specific label
  type: ClusterIP             # specifies the service type i.e cluster IP or NodePort
  ports:
  - port: 80
    targetPort: 80
